name: Test

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 11,25 * *' # roughly every two weeks to run on new Ruby versions
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: "Unit"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ruby:
          - "2.1"
          - "2.2"
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "head"
        exclude:
          # Windows doesn't have 3.0, so run head there but nowhere else.
          - { ruby: "head", os: "macos-latest" }
          - { ruby: "head", os: "ubuntu-latest" }
          - { ruby: "3.0", os: "windows-latest" }

    steps:

    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test
      run: bundle exec rake

  system:
    name: "System"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ruby:
          - "2"
          - "3.0"
          - "head"
          - "jruby"
          - "truffleruby"
        exclude:
          # Windows doesn't have 3.0, so run head there but nowhere else.
          - { ruby: "head", os: "macos-latest" }
          - { ruby: "head", os: "ubuntu-latest" }
          - { ruby: "3.0", os: "windows-latest" }
          # Windows releases of jruby and truffleruby have issues. Skip them for now.
          - { ruby: "jruby", os: "windows-latest" }
          - { ruby: "truffleruby", os: "windows-latest" }

    steps:

    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install gem
      run: bundle exec rake install

    - name: Create directory for gem test
      run: mkdir -p tmp/gem-test

    - name: Create test Gemfile
      run: echo "gem 'debug_inspector'" > Gemfile
      working-directory: ./tmp/gem-test

    - name: Test gem load
      run: bundle exec ruby -e "require 'debug_inspector'"

    - name: Test gem functionality
      if: ${{ matrix.ruby != 'jruby' && matrix.ruby != 'truffleruby' }}
      run: bundle exec ruby -e "require 'debug_inspector'; RubyVM::DebugInspector.open { |dc| dc.frame_binding(1) }"
